name: heeroyuy7-sync
on:
  schedule:
    - cron: '1 */6 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: heeroyuy7
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync heeroyuy7
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/heeroyuy7/heeroyuy7.git"
          source_branch: "master"
          destination_branch: "master"
          github_token: ${{ secrets.PAT }}
